export const GET_SENT_MAIL_START = 'GET_SENT_MAIL_START';
export const GET_SENT_MAIL_SUCCESS = 'GET_SENT_MAIL_SUCCESS';
export const GET_SENT_MAIL_FAIL = 'GET_SENT_MAIL_FAIL';
export const ADD_NEW_SENT_MAIL = 'ADD_NEW_SENT_MAIL';
export const ADD_NEW_LIST_SENT_MAIL = 'ADD_NEW_LIST_SENT_MAIL';
