export const GET_GUEST_START = 'GET_GUEST_START';
export const GET_GUEST_SUCCESS = 'GET_GUEST_SUCCESS';
export const ADD_GUEST_SUCCESS = 'ADD_GUEST_SUCCESS';
export const UPDATE_GUEST_SUCCESS = 'UPDATE_GUEST_SUCCESS';
export const GET_GUEST_FAIL = 'GET_GUEST_FAIL';
export const CLEAR_GUEST_REDUCER = 'CLEAR_GUEST_REDUCER';
export const RESET_ADD_UPDATE_GUEST_REDUCER = 'RESET_ADD_UPDATE_GUEST_REDUCER';
