export const GET_OUT_BOX_START = 'GET_OUT_BOX_START';
export const GET_OUT_BOX_SUCCESS = 'GET_OUT_BOX_SUCCESS';
export const GET_OUT_BOX_FAIL = 'GET_OUT_BOX_FAIL';
export const ADD_NEW_OUTBOX_MAIL = 'ADD_NEW_OUTBOX_MAIL';
export const DELETE_OUTBOX_MAIL = 'DELETE_OUTBOX_MAIL';
