export const GET_MARITAL_STATUS_START = 'GET_MARITAL_STATUS_START';
export const GET_MARITAL_STATUS_SUCCESS = 'GET_MARITAL_STATUS_SUCCESS';
export const GET_MARITAL_STATUS_FAIL = 'GET_MARITAL_STATUS_FAIL';
