export const GET_GOAL_START = 'GET_GOAL_START';
export const GET_GOAL_SUCCESS = 'GET_GOAL_SUCCESS';
export const GET_GOAL_FAIL = 'GET_GOAL_FAIL';
export const ADD_GOAL_SUCCESS = 'ADD_GOAL_SUCCESS';
export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS';
export const CLEAR_GOAL_REDUCER = 'CLEAR_GOAL_REDUCER';
export const RESET_ADD_UPDATE_GOAL_REDUCER = 'RESET_ADD_UPDATE_GOAL_REDUCER';

