export const GET_TODO_START = 'GET_TODO_START';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const GET_TODO_FAIL = 'GET_TODO_FAIL';
export const CLEAR_TODO_REDUCER = 'CLEAR_TODO_REDUCER';
export const RESET_ADD_UPDATE_TODO_REDUCER = 'RESET_ADD_UPDATE_TODO_REDUCER';
