export const screenNames = {
  LOGIN_SCREEN: 'Login',
  DASHBOARD_SCREEN: 'Dashboard',
  MAIL_COMPOSE_SCREEN: 'Compose Mail',
  INBOX_SCREEN: 'Inbox Mail',
  OUTBOX_SCREEN: 'Outbox Mail',
  SENT_SCREEN: 'Sent Mail',
  PDF_VIEWER_SCREEN: 'PDF Viewer',
  CHANGE_PASSWORD_SCREEN: 'Change Password',
  PROFILE_SCREEN: 'My Profile',
  PROFILE_BASIC_INFO_SCREEN: 'Basic',
  PROFILE_FIRST_POINT_SCREEN: 'First Point',
  PROFILE_OFFICIAL_INFO_SCREEN: 'Official',
  PROFILE_DOCUMENTS_SCREEN: 'Documents',
  PROFILE_TAB_SCREEN: 'Profile',
  EMPLOYEE_SCREEN: 'Employees',
  CALENDAR_SCREEN: 'Calendar',
  MAIL_SCREEN: 'Mail',
  ORGANIZER_SCREEN: 'Organizer',
  BUSINESS_DUE_DATE_SCREEN: 'Business Due Date',
  GOAL_SCREEN: 'Goal',
  MEETING_SCREEN: 'Meeting Schedule',
  ADD_MEETING_SCREEN: 'Meeting Entry',
  AGENDA_MINUTE_SCREEN: 'Agenda And Minute',
  TASK_SCREEN: 'Task',
  PERSON_SCREEN: 'Person',
  PERSON_DETAIL_SCREEN: 'Person Detail',
  COMPANY_SCREEN: 'Company',
  COMPANY_EDIT_DETAIL_SCREEN: 'Company Detail Edit',
  COMPANY_DETAIL_SCREEN: 'Company Detail',
  ADD_GOALS_SCREEN: 'Goal Entry',
  HOLIDAY_SCREEN: 'Holiday',
  ADD_HOLIDAY_SCREEN: 'Holiday Entry',
  GUEST_SCREEN: 'Guest',
  ADD_GUEST_SCREEN: 'Guest Entry',
  APPOINTMENT_SCREEN: 'Appointments',
  ADD_APPOINTMENT_SCREEN: 'Appointment Entry',
  TODO_SCREEN: 'Todos',
  ADD_TODO_SCREEN: 'Todo Entry',
  LEAVE_LIST_SCREEN: 'Applied Leaves',
  LEAVE_SCREEN: 'Apply Leave',
  LOAN_LIST_SCREEN: 'Applied Loans',
  LOAN_SCREEN: 'Loan Screen',
  EMAIL_DETAIL_SCREEN: 'Message Detail',
  COMPOSE_INTERNAL_SCREEN: 'Compose Internal',
  IMAGE_VIEWER_SCREEN: 'Image Viewer',
  TENDER_SCREEN: 'Tender',
  TENDER_DETAIL_SCREEN: 'Tender Detail Screen',
  TENDER_EXTENSION_SCREEN: 'Tender Extension Screen',
  CONTRACT_SCREEN: 'Contract Screen',
  PROJECT_SCREEN: 'Project Screen',
  PROJECT_DETAIL_SCREEN: 'Project Detail Screen',
  REFERENCE_SCREEN: 'Reference Screen',
  OTHER_SCREEN: 'Other Screen',
  REFERENCE_TASK_SCREEN: 'Reference Task Screen',
  REFERENCE_FEES_SCREEN: 'Reference Fees Screeen',
  REFERENCE_REPORT_SCREEN: 'Reference Report Screen',
  REFERENCE_TASK_SCREEN: 'Reference Task Screen',
  CONTACT_SCREEN: 'Contact',
  TENDER_SUMMARY: 'Tender Summary',
  TENDER_COMPANIES: 'Tender Companies',
  TENDER_TASKS: 'Tender Tasks',
  TENDER_DOCS: 'Tender Docs',
};

export const navScreenNames = {
  NAV_LOGIN_SCREEN: 'LoginScreen',
  NAV_DASHBOARD_SCREEN: 'DashboardScreen',
  NAV_MAIL_COMPOSE_SCREEN: 'ComposeMailScreen',
  NAV_INBOX_SCREEN: 'InboxScreen',
  NAV_OUTBOX_SCREEN: 'OutboxMailScreen',
  NAV_SENT_SCREEN: 'SentMailScreen',
  NAV_PDF_VIEWER_SCREEN: 'PdfViewerScreen',
  NAV_CHANGE_PASSWORD_SCREEN: 'ChangePasswordScreen',
  NAV_PROFILE_SCREEN: 'ProfileScreen',
  NAV_PROFILE_BASIC_INFO_SCREEN: 'ProfileBasicInfoScreen',
  NAV_PROFILE_FIRST_POINT_SCREEN: 'ProfileFirstPointScreen',
  NAV_PROFILE_OFFICIAL_INFO_SCREEN: 'ProfileOfficialInfoScreen',
  NAV_PROFILE_DOCUMENTS_SCREEN: 'ProfileDocumentsScreen',
  NAV_PROFILE_DOCUMENTS_SCREEN: 'ProfileDocumentsScreen',
  NAV_DOCUMENT_TAB_SCREEN: 'ProfileDocumentsScreen',
  NAV_PROFILE_TAB_ROUTE: 'NavProfileRoute',
  NAV_DRAWER_ROUTE: 'NavDrawerRoute',
  NAV_MAIL_ROUTE: 'NavMailRoute',
  NAV_ORGANIZER_ROUTE: 'NavOrganizerRoute',
  NAV_CONTACT_ROUTE: 'NavContactRoute',
  NAV_BOTTOM_TAB_ROUTE: 'NavBottomTabRoute',
  NAV_HR_DRAWER_TAB_ROUTE: 'NavHrRoute',
  NAV_EMPLOYEE_SCREEN: 'EmployeeScreen',
  NAV_LOG_OUT: 'NavLogout',
  NAV_SPLASH_SCREEN: 'SplashScreen',
  NAV_CALENDAR_SCREEN: 'CalendarScreen',
  NAV_MAIL_SCREEN: 'MailScreen',
  NAV_ORGANIZER_SCREEN: 'OrganizerScreen',
  NAV_BUSINESS_DUE_DATE_SCREEN: 'BusinessDueDateScreen',
  NAV_GOAL_SCREEN: 'GoalScreen',
  NAV_MEETING_SCREEN: 'MeetingScreen',
  NAV_AGENDA_MINUTE_SCREEN: 'AgendaMinuteScreen',
  NAV_ADD_MEETING_SCREEN: 'AddMeetingScreen',
  NAV_TASK_SCREEN: 'TaskScreen',
  NAV_PERSON_SCREEN: 'PersonScreen',
  NAV_PERSON_DETAIL_SCREEN: 'PersonDetailScreen',
  NAV_COMPANY_SCREEN: 'CompanyScreen',
  NAV_COMPANY_EDIT_DETAIL_SCREEN: 'CompanyEditDetailScreen',
  NAV_COMPANY_DETAIL_SCREEN: 'CompanyDetailScreen',
  NAV_COMPANY_PERSONS_SCREEN: 'CompanyPersonsScreen',
  NAV_COMPANY_DETAIL_TAB_ROUTE: 'CompanyDetailTabRoute',
  NAV_ADD_GOALS_SCREEN: 'AddGoalsScreen',
  NAV_HOLIDAY_SCREEN: 'HolidayScreen',
  NAV_ADD_HOLIDAY_SCREEN: 'AddHolidayScreen',
  NAV_GUEST_SCREEN: 'GuestScreen',
  NAV_ADD_GUEST_SCREEN: 'AddGuestScreen',
  NAV_ADD_APPOINTMENT_SCREEN: 'AddAppointmentScreen',
  NAV_APPOINTMENT_SCREEN: 'AppointmentScreen',
  NAV_ADD_TODO_SCREEN: 'AddTodoScreen',
  NAV_TODO_SCREEN: 'TodoScreen',
  NAV_LOAN_SCREEN: 'LoanScreen',
  NAV_LOAN_LIST_SCREEN: 'LoanListScreen',
  NAV_LEAVE_SCREEN: 'LeaveScreen',
  NAV_LEAVE_LIST_SCREEN: 'LeaveListScreen',
  NAV_EMAIL_DETAIL_SCREEN: 'EmailViewScreen',
  NAV_COMPOSE_INTERNAL_SCREEN: 'ComposeInternalScreen',
  NAV_IMAGE_VIEWER_SCREEN: 'ImageViewerScreen',
  NAV_TENDER_SCREEN: 'TenderScreen',
  NAV_TENDER_DETAIL_SCREEN: 'TenderDetailScreen',
  NAV_CONTRACT_SCREEN: 'ContractScreen',
  NAV_PROJECT_SCREEN: 'ProjectScreen',
  NAV_PROJECT_DETAIL_SCREEN: 'ProjectDetailScreen',
  NAV_REFERENCE_SCREEN: 'ReferenceScreen',
  NAV_OTHER_SCREEN: 'OtherScreen',
  NAV_REFERENCE_COMPANY_SCREEN: 'ReferenceCompanyScreen',
  NAV_REFERENCE_FEES_SCREEN: 'ReferenceFeeScreen',
  NAV_REFERENCE_REPORT_SCREEN: 'ReferenceReportScreen',
  NAV_REFERENCE_TASK_SCREEN: 'ReferenceTaskScreen',
  NAV_TENDER_EXTENSION: 'TenderExtensions',
  NAV_CONTACT_SCREEN: 'Contact',
  NAV_TENDER_SUMMARY: 'TenderSummary',
  NAV_TENDER_COMPANIES: 'TenderCompanies',
  NAV_TENDER_TASKS: 'TenderTasks',
  NAV_TENDER_DOCS: 'TenderDocs',
};

export const WarningTypes = {
  SUCCESS: 'success-warning',
  FAILED: 'failed-warning',
  INFO: 'info-warning',
};

export const WarningLength = {
  VERY_LONG: 5000,
  LONG: 3000,
  SHORT: 1000,
};

export const AsyncStoreKeys = {
  AUTH_TOKEN: 'Async-Auth-token',
  FCM_TOKEN: 'Async-FCM-token',
  AUTH_TOKEN_EXPIRY: 'Async-Auth-Token-Expiry',
  REFRESH_TOKEN: 'Async-Refresh-Token',
  USER_ID: 'Async-User-Id',
  USER_ROLE: 'Async-User-Role',
};

export const Ids = {
  NOTIFICATION_CHANNEL_ID: '007',
  NOTIFICATION_CHANNEL_NAME: 'Push Notification Channel',
  FB_APP_ID: '',
  GOOGLE_CLIENT_ID: '',
};
