export const GET_MEETING_START = 'GET_MEETING_START';
export const GET_MEETING_SUCCESS = 'GET_MEETING_SUCCESS';
export const ADD_MEETING_SUCCESS = 'ADD_MEETING_SUCCESS';
export const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS';
export const GET_MEETING_FAIL = 'GET_MEETING_FAIL';
export const CLEAR_MEETING_REDUCER = 'CLEAR_MEETING_REDUCER';
export const RESET_ADD_UPDATE_MEETING_REDUCER =
  'RESET_ADD_UPDATE_MEETING_REDUCER';
