export const GET_EMPLOYEE_START = 'GET_EMPLOYEE_START';
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_SUCCESS_PAGE = 'GET_EMPLOYEE_SUCCESS_PAGE';
export const GET_EMPLOYEE_FAIL = 'GET_EMPLOYEE_FAIL';
