export const GET_APPOINTMENT_START = 'GET_APPOINTMENT_START';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAIL = 'GET_APPOINTMENT_FAIL';
export const CLEAR_APPOINTMENT_REDUCER = 'CLEAR_APPOINTMENT_REDUCER';
export const RESET_ADD_UPDATE_APPOINTMENT_REDUCER =
  'RESET_ADD_UPDATE_APPOINTMENT_REDUCER';
